USE [master]
GO

/****** Object:  Database [tritonexpress]    Script Date: 2022/07/31 15:47:19 ******/
CREATE DATABASE [tritonexpress]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tritonexpress', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\tritonexpress.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tritonexpress_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\tritonexpress_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tritonexpress].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tritonexpress] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tritonexpress] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tritonexpress] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tritonexpress] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tritonexpress] SET ARITHABORT OFF 
GO

ALTER DATABASE [tritonexpress] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tritonexpress] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tritonexpress] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tritonexpress] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tritonexpress] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tritonexpress] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tritonexpress] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tritonexpress] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tritonexpress] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tritonexpress] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tritonexpress] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tritonexpress] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tritonexpress] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tritonexpress] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tritonexpress] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tritonexpress] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tritonexpress] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tritonexpress] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tritonexpress] SET  MULTI_USER 
GO

ALTER DATABASE [tritonexpress] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tritonexpress] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tritonexpress] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tritonexpress] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [tritonexpress] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tritonexpress] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [tritonexpress] SET QUERY_STORE = OFF
GO

ALTER DATABASE [tritonexpress] SET  READ_WRITE 
GO


